# Generated by Django 5.1.1 on 2024-11-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_application_category_alter_application_at_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('leave', '休暇申請'), ('correction', '打刻訂正申請')], default='leave', max_length=20, verbose_name='申請カテゴリー'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='申請日'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(verbose_name='申請内容'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', '保留中'), ('approved', '承認済み'), ('rejected', '却下済み')], default='pending', max_length=10, verbose_name='ステータス'),
        ),
    ]
