# Generated by Django 5.1.1 on 2024-11-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('leave', '休暇申請'), ('correction', '打刻訂正申請')], default='leave', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='at_date',
            field=models.DateField(),
        ),
    ]
