# Generated by Django 5.1.1 on 2024-11-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_application_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.CharField(choices=[('休暇', '休暇申請'), ('打刻訂正', '打刻訂正申請')], default='休暇', max_length=20, verbose_name='申請カテゴリー'),
        ),
    ]
